fallback = 'ï‹ '
separator = '  '

# These are tested in order; the first pattern that matches, wins.
[matching]
# config
'/\.conf$/' = 'î˜•'
'/\.doc$/' = 'ïœ«'
'/\.exe$/' = 'îœ'
'/\.ini$/' = 'î˜•'
'/\.json$/' = 'î˜‹'
'/\.md$/' = 'î˜‰'
'/\.mdx$/' = 'î˜‰'
'/\.pdf$/' = 'ïœ¤'
'/\.ppt$/' = 'ïœ¦'
'/\.toml$/' = 'î˜•'
'/\.xls$/' = 'ïœš'
'/\.xml$/' = 'ï‡‰'
'/\.yam$/' = 'î˜•'
'/\.yaml$/' = 'î˜•'

# languages
'/\.ai$/'       = 'î´'
'/\.c$/'        = 'î˜'
'/\.c++$/'      = 'î˜'
'/\.cc$/'       = 'î˜'
'/\.clj$/'      = 'î¨'
'/\.cljc$/'     = 'î¨'
'/\.cljs$/'     = 'îª'
'/\.coffee$/'   = 'î˜›'
'/\.cp$/'       = 'î˜'
'/\.cpp$/'      = 'î˜'
'/\.cs$/'       = 'ï š'
'/\.css$/'      = 'î˜”'
'/\.cxx$/'      = 'î˜'
'/\.d$/'        = 'î¯'
'/\.dart$/'     = 'î˜'
'/\.db$/'       = 'îœ†'
'/\.diff$/'     = 'îœ¨'
'/\.dump$/'     = 'îœ†'
'/\.edn$/'      = 'îª'
'/\.eex$/'      = 'î˜­'
'/\.elm$/'      = 'î˜¬'
'/\.erl$/'      = 'î±'
'/\.ex$/'       = 'î˜­'
'/\.exs$/'      = 'î˜­'
'/\.f#$/'       = 'î§'
'/\.fs$/'       = 'î§'
'/\.fsi$/'      = 'î§'
'/\.fsscript$/' = 'î§'
'/\.fsx$/'      = 'î§'
'/\.gemspec$/'  = 'î‘'
'/\.go$/'       = 'î˜§'
'/\.h$/'        = 'ïƒ½'
'/\.heex$/'     = 'î˜­'
'/\.hh$/'       = 'ïƒ½'
'/\.hpp$/'      = 'ïƒ½'
'/\.hrl$/'      = 'î±'
'/\.hs$/'       = 'î˜Ÿ'
'/\.html$/'     = 'î˜'
'/\.hxx$/'      = 'ïƒ½'
'/\.java$/'     = 'îœ¸'
'/\.jl$/'       = 'î˜¤'
'/\.js$/'       = 'î˜Œ'
'/\.jsx$/'      = 'îº'
'/\.leex$/'     = 'î˜­'
'/\.less$/'     = 'î˜”'
'/\.lhs$/'      = 'î˜Ÿ'
'/\.lua$/'      = 'î˜ '
'/\.mjs$/'      = 'î˜Œ'
'/\.ml$/'       = 'Î»'
'/\.mli$/'      = 'Î»'
'/\.nix$/'      = 'ïŒ“'
'/\.pem$'      = 'ï Š'
'/\.php$/'      = 'î˜ˆ'
'/\.pl$/'       = 'î©'
'/\.pm$/'       = 'î©'
'/\.pp$/'       = 'ï’™'
'/\.psb$/'      = 'î¸'
'/\.psd$/'      = 'î¸'
'/\.py$/'       = 'ï¢'
'/\.pyc$/'      = 'ï¢'
'/\.pyd$/'      = 'ï¢'
'/\.pyo$/'      = 'ï¢'
'/\.r$/'       = 'ï³’'
'/\.rake$/'     = 'î‘'
'/\.rb$/'       = 'î‘'
'/\.rlib$/'     = 'î¨'
'/\.rproj$'    = 'ï«…'
'/\.rs$/'       = 'î¨'
'/\.rss$/'      = 'î˜™'
'/\.sass$/'     = 'î˜ƒ'
'/\.scala$/'    = 'îœ·'
'/\.scss$/'     = 'î˜ƒ'
'/\.sh$/'       = 'î'
'/\.sln$/'      = 'îœŒ'
'/\.sql$/'      = 'îœ†'
'/\.suo$/'      = 'îœŒ'
'/\.swift$/'    = 'î•'
'/\.t$/'        = 'î©'
'/\.ts$/'       = 'î˜¨'
'/\.tsx$/'      = 'îº'
'/\.twig$/'     = 'î˜œ'
'/\.vim$/'      = 'î˜«'
'/\.xcplayground$/'    = 'î•'
'/\.xul$/'      = 'î…'

# image extension
'/\.bmp$/' = 'î˜'
'/\.gif$/' = 'î˜'
'/\.ico$/' = 'î˜'
'/\.jpeg$/' = 'î˜'
'/\.jpg$/' = 'î˜'
'/\.png$/' = 'î˜'
'/\.webp$/' = 'î˜'

# Terminals
'/nvim/' = 'î˜«'

'/nix/' = 'ïŒ“'
'/git/' = 'îœ‚'
'/lazygit/' = 'îœ‚'
'/diff/' = 'îœ¨'

# editors
'Code' = 'îœŒ'
'code-oss' = 'îœŒ'
'code-url-handler' = 'îœŒ'

'jetbrains-idea-ce' = 'IJ'
'jetbrains-studio' = 'IJ'

'/npm/' = 'îœ˜'
'/node_modules/' = 'îœ˜'
'/node/' = 'îœ˜'
'/yarn/' = 'îœ˜'

# browsers
# more specific higher order
'/(?i).*Invidious.*Firefox/' = 'ï€½'
'/(?i)Github.*Firefox/' = 'ï„“'
'/(?i)Github/' = 'ï‚›'
'/(?i)Gitlab.*Firefox/' = 'ïŠ–'
'/(?i)Google Calendar.*Firefox/' = 'ï³'
'/(?i)drive.*Firefox/' = 'ïª'
'/(?i)h2.*Firefox/' = 'îœ†'
'/(?i)reddit.*Firefox/' = 'ïŠ'
'/Firefox .*Private Browsing/' = 'ï°'
'/(?i)Google-chrome/' = 'ï‰¨'
'Nightly' = 'ï‰©'
'Tor Browser' = 'î§'
'brave-browser' = 'ï‰¨'
'chromium' = 'ï‰¨'
'firefox' = 'ï‰©'
'firefoxdeveloperedition' = 'ï‰©'

# app
'openaws-vpn-client' = 'ï­'
'kitty' = 'ï„ '
'Alacritty' = 'ï„ '
'Bitwarden' = 'ï‚„'
'FreeFileSync' = 'ï‹±'
'GParted' = 'ïƒ‡'
'Gimp' = 'ï‡»'
'GitHub Desktop' = 'ï„“'
'google-chrome' = 'ï‰¨'
'Insomnia' = 'ïˆ¶'
'Pinta' = 'ğŸ–Œ'
'/(?i)Signal/' = 'ïµ'
'Slack' = 'ï†˜'
'Steam' = 'ï†¶'
'Thunderbird' = 'ïƒ '
'anki' = 'ï€…'
'balena-etcher' = 'ï‹›'
'blueberry.py' = 'ïŠ“'
'calculator' = 'ï—«'
'calibre-gui' = 'ï€­'
'com.github.tenderowl.frog' = 'ï€‚'
'com.gitlab.zehkira.Myuzi' = 'ï€'
'com.nextcloud.desktopclient.nextcloud' = 'ïƒ‚'
'czkawka-gui' = 'ï‹±'
'discord' = 'ï’'
'eog' = 'ï†‡'
'filezilla' = 'ï¼'
'galculator' = 'ğŸ–©'
'gimagereader-gtk' = 'ï€‚'
'gimagereader-qt' = 'ï€‚'
'github' = 'ï„“'
'libreoffice' = 'ï£…'
'libreoffice-calc' = 'ïƒ'
'libreoffice-writer' = 'ïœ˜'
'menu' = 'ï¡œ'
'mpd' = 'ï€'
'mpv' = 'ï€½'
'ncmpcpp' = 'ï€'
'nemo' = 'ï¼'
'nuclear' = 'ï€'
'obs' = 'ï†’'
'org.gnome.Nautilus' = 'ï†‡'
'org.kde.ark' = 'ï¼'
'org.kde.digikam' = 'ğŸ–Œ'
'org.ksnip.ksnip' = 'ğŸ–Œ'
'org.qbittorrent.qBittorrent' = 'ï¶'
'org.telegram.desktop' = 'ïµ'
'pamac-manager' = 'ï¯'
'pavucontrol' = 'ï€¨'
'telegramdesktop' = 'ïµ'
'tenacity' = 'ï€'
'thunar' = 'ï¼'
'transmission' = 'ï€™'
'videostream' = 'ï˜˜'
'vimiv' = 'î˜'
'virt-manager' = 'ï†²'
'vlc' = 'ï€½'
'wdisplays' = 'ğŸ–µ'
